-- local wezterm = require("wezterm")
-- local act = wezterm.action
--
-- local M = {}
--
-- function M.apply_to_config(config)
-- 	wezterm.on("user-var-changed", function(window, pane, name, value)
-- 		if name == "MOVE_TO_NEXT_MONITOR" then
-- 			local current_window = window:gui_window()
-- 			local current_screen = current_window:current_screen()
-- 			local screens = wezterm.gui.screens()
--
-- 			local current_screen_index = -1
-- 			for i, screen in ipairs(screens) do
-- 				-- ピクセル座標で現在のスクリーンを特定
-- 				if
-- 					screen.pixel_coords.x == current_screen.pixel_coords.x
-- 					and screen.pixel_coords.y == current_screen.pixel_coords.y
-- 				then
-- 					current_screen_index = i
-- 					break
-- 				end
-- 			end
--
-- 			if current_screen_index ~= -1 then
-- 				-- 次のモニターのインデックスを計算（循環）
-- 				local next_screen_index = (current_screen_index % #screens) + 1
-- 				local next_screen = screens[next_screen_index]
--
-- 				-- ウィンドウの現在のサイズを取得
-- 				local current_width, current_height = current_window:dimensions()
--
-- 				-- 次のモニターの中央に移動させるための新しい座標を計算
-- 				-- ウィンドウのサイズを考慮して、新しいモニターの中央に配置
-- 				local new_x = next_screen.pixel_coords.x + (next_screen.width - current_width) / 2
-- 				local new_y = next_screen.pixel_coords.y + (next_screen.height - current_height) / 2
--
-- 				-- 最大化されている場合は、一度解除してから移動し、再度最大化
-- 				local was_maximized = current_window:is_maximized()
-- 				if was_maximized then
-- 					current_window:unmaximize()
-- 				end
--
-- 				-- ウィンドウを新しい位置に移動
-- 				current_window:set_position(new_x, new_y)
--
-- 				if was_maximized then
-- 					current_window:maximize()
-- 				end
-- 			end
-- 		end
-- 	end)
--
-- 	-- ウィンドウ移動用のキーバインドをキーバインドリストに追加
-- 	-- wezterm.add_to_config_table は config.keys に配列を直接追加できないため、
-- 	-- キーバインドをマージする必要があります。
-- 	-- あるいは、keybindings.lua に直接移動キーバインドを追加する方がシンプルです。
-- 	-- ここでは、wezterm.lua でキーバインドを統合する例を想定して、
-- 	-- apply_to_config 関数内で直接 config.keys に追加します。
-- 	-- keybindings.lua の apply_to_config 関数にこのキーバインドを追加することも可能です。
-- 	table.insert(config.keys, {
-- 		key = "m",
-- 		mods = "ALT", -- 例: Alt+m で移動
-- 		action = wezterm.action_callback(function(win, pane)
-- 			win:set_user_var("MOVE_TO_NEXT_MONITOR", "true")
-- 		end),
-- 	})
-- end
--
-- return M
